name: Deploy Contract
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/midnightntwrk/compact/releases/latest/download/compact-installer.sh | sh
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: |
          compact update
          compact compile contracts/voting.compact public/keys
          compact compile contracts/voting.compact src/services/midnight/managed/voting
      - run: npm ci
        working-directory: ./preprod-deployment
      - run: npm ci
        working-directory: ./preprod-deployment/cli
      - run: npm run build
        working-directory: ./preprod-deployment/cli
      - name: Run Deploy
        working-directory: ./preprod-deployment/cli
        env:
          WALLET_SEED: "salon artwork special sleep twice travel rare region summer beach toss machine husband stove drive shuffle plunge assist seed income twin drama grid skirt"
        run: |
          npm run start deploy-voting > deploy_output.log
          cat deploy_output.log
          # Extract contract address
          ADDRESS=$(grep -oP 'Contract Address: \K[a-f0-9]+' deploy_output.log | tail -n 1)
          if [ -z "" ]; then
            echo "Failed to find contract address"
            exit 1
          fi
          echo "{\"address\": \"$ADDRESS"\}" > ../../deployed_contract.json
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add deployed_contract.json
          git commit -m "Deploy new contract address"
          git push
